---
- name: check for existing install...
  become: yes
  become_user: root
  stat:
    path: '{{ nexus_repo_install_dir }}'
  changed_when: False
  register: nexus_repo_binary
- when: not nexus_repo_binary.stat.exists
  block:
    - name: download...
      become: yes
      become_user: root
      get_url:
        url: '{{ nexus_repo_tgz_url }}'
        dest: /tmp/{{ nexus_repo_tgz }}
        checksum: '{{ nexus_repo_checksum }}'
        mode: 0644
    - name: unarchive...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ nexus_repo_tgz }}
        dest: '{{ nexus_repo_parent_install_dir }}'
        creates: '{{ nexus_repo_install_dir }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ nexus_repo_tgz }}
        state: absent

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{ nexus_repo_install_dir }}'
    dest: '{{ nexus_repo_link_dir }}'
    state: link

- name: add to PATH...
  become: yes
  become_user: root
  with_items:
    - f: nexus.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
